app = "facilix"
primary_region = "sin"

[[vm]]
cpus = 2
memory_mb = 4096
cpu_kind = "performance"

[[services]]
internal_port = 8000
protocol = "tcp"
auto_start_machines = false
auto_stop_machines = true
min_machines_running = 0

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls"]

[[services.http_checks]]
interval = "15s"
timeout = "5s"
grace_period = "10s"
method = "get"
path = "/health/live"
protocol = "http"
