"""Data models for IoT sensor devices and their telemetry readings."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class SensorType(str, Enum):
    """Supported sensor measurement categories."""

    TEMPERATURE = "temperature"
    HUMIDITY = "humidity"
    PRESSURE = "pressure"
    LIGHT = "light"
    MOTION = "motion"
    AIR_QUALITY = "air_quality"
    LEAK = "leak"
    VIBRATION = "vibration"
    DOOR_CONTACT = "door_contact"
    BATTERY = "battery"


class SensorStatus(str, Enum):
    """Operational status of a sensor device."""

    OK = "ok"
    DEGRADED = "degraded"
    OFFLINE = "offline"
    ERROR = "error"


# ---------------------------------------------------------------------------
# Device definition
# ---------------------------------------------------------------------------


@dataclass
class SensorDevice:
    """Describes one virtual sensor device."""

    device_id: str
    sensor_type: SensorType
    label: str
    status: SensorStatus = SensorStatus.OK
    interval_seconds: int = 5
    battery_pct: float = 100.0
    signal_rssi_dbm: int = -55

    # Measurement bounds for realistic random generation
    value_min: float = 0.0
    value_max: float = 100.0
    value_unit: str = ""
    value_decimals: int = 1

    # Optional secondary value (e.g., occupancy count for motion)
    secondary_label: str = ""
    secondary_min: float = 0.0
    secondary_max: float = 0.0
    secondary_unit: str = ""

    # Current "drift anchor" so values change smoothly
    _current_value: float = 0.0
    _current_secondary: float = 0.0


# ---------------------------------------------------------------------------
# Telemetry readings
# ---------------------------------------------------------------------------


@dataclass
class SensorReading:
    """A single telemetry reading generated by a sensor device."""

    device_id: str
    sensor_type: SensorType
    timestamp: datetime
    sequence: int
    status: SensorStatus
    battery_pct: float
    signal_rssi_dbm: int
    value: float
    unit: str
    secondary_value: Optional[float] = None
    secondary_unit: Optional[str] = None

    def to_facilix_payload(self) -> Dict[str, Any]:
        """Default Facilix-format payload."""
        values: Dict[str, Any] = {
            self.sensor_type.value: {
                "value": round(self.value, 2),
                "unit": self.unit,
            }
        }
        if self.secondary_value is not None and self.secondary_unit is not None:
            extra_label = "occupancy" if self.sensor_type == SensorType.MOTION else "value"
            values[extra_label] = {
                "value": round(self.secondary_value, 2),
                "unit": self.secondary_unit,
            }

        return {
            "deviceId": self.device_id,
            "sensorType": self.sensor_type.value,
            "timestamp": self.timestamp.isoformat(),
            "sequence": self.sequence,
            "status": self.status.value,
            "batteryPct": round(self.battery_pct, 1),
            "signalRssiDbm": self.signal_rssi_dbm,
            "values": values,
        }

    def to_thingsboard_payload(self) -> Dict[str, Any]:
        """ThingsBoard MQTT-style telemetry payload."""
        return {
            "ts": int(self.timestamp.timestamp() * 1000),
            "values": {
                self.sensor_type.value: round(self.value, 2),
                **({"occupancy": round(self.secondary_value, 2)} if self.secondary_value is not None else {}),
            },
        }

    def to_senml_payload(self) -> List[Dict[str, Any]]:
        """SenML (RFC 8428) compact representation."""
        records: List[Dict[str, Any]] = [
            {
                "n": self.sensor_type.value,
                "u": self.unit,
                "v": round(self.value, 2),
                "t": int(self.timestamp.timestamp()),
            }
        ]
        if self.secondary_value is not None and self.secondary_unit is not None:
            records.append(
                {
                    "n": "occupancy",
                    "v": round(self.secondary_value, 0),
                    "t": int(self.timestamp.timestamp()),
                }
            )
        records.append(
            {
                "n": "battery",
                "u": "%",
                "v": round(self.battery_pct, 1),
                "t": int(self.timestamp.timestamp()),
            }
        )
        records.append(
            {
                "n": "signal",
                "u": "dBm",
                "v": self.signal_rssi_dbm,
                "t": int(self.timestamp.timestamp()),
            }
        )
        return records

    def to_dict(self, fmt: str = "facilix") -> Dict[str, Any]:
        """Convert to dict in the requested format."""
        if fmt == "thingsboard":
            return self.to_thingsboard_payload()
        if fmt == "senml":
            return {"senml": self.to_senml_payload()}
        return self.to_facilix_payload()


# ---------------------------------------------------------------------------
# Sensor definition presets
# ---------------------------------------------------------------------------

SENSOR_DEFINITIONS: List[SensorDevice] = [
    SensorDevice(
        device_id="sensor-temp-001",
        sensor_type=SensorType.TEMPERATURE,
        label="Temperature Sensor — Main Lobby",
        value_min=18.0,
        value_max=30.0,
        value_unit="°C",
        value_decimals=1,
    ),
    SensorDevice(
        device_id="sensor-humidity-001",
        sensor_type=SensorType.HUMIDITY,
        label="Humidity Sensor — Warehouse A",
        value_min=30.0,
        value_max=70.0,
        value_unit="%RH",
        value_decimals=1,
    ),
    SensorDevice(
        device_id="sensor-pressure-001",
        sensor_type=SensorType.PRESSURE,
        label="Barometric Pressure — Outdoor",
        value_min=980.0,
        value_max=1040.0,
        value_unit="hPa",
        value_decimals=1,
    ),
    SensorDevice(
        device_id="sensor-light-001",
        sensor_type=SensorType.LIGHT,
        label="Ambient Light — Office South",
        value_min=0.0,
        value_max=1200.0,
        value_unit="lux",
        value_decimals=0,
    ),
    SensorDevice(
        device_id="sensor-motion-001",
        sensor_type=SensorType.MOTION,
        label="Motion Detector — Corridor B",
        value_min=0.0,
        value_max=1.0,
        value_unit="detected",
        value_decimals=0,
        secondary_label="occupancy_count",
        secondary_min=0.0,
        secondary_max=15.0,
        secondary_unit="people",
    ),
    SensorDevice(
        device_id="sensor-air-001",
        sensor_type=SensorType.AIR_QUALITY,
        label="Air Quality — Server Room",
        value_min=350.0,
        value_max=1200.0,
        value_unit="ppm",
        value_decimals=0,
        secondary_label="voc",
        secondary_min=0.0,
        secondary_max=500.0,
        secondary_unit="ppb",
    ),
    SensorDevice(
        device_id="sensor-leak-001",
        sensor_type=SensorType.LEAK,
        label="Leak Detector — Boiler Room",
        value_min=0.0,
        value_max=1.0,
        value_unit="leak",
        value_decimals=0,
    ),
    SensorDevice(
        device_id="sensor-vibration-001",
        sensor_type=SensorType.VIBRATION,
        label="Vibration Sensor — Pump Unit 3",
        value_min=0.0,
        value_max=25.0,
        value_unit="mm/s",
        value_decimals=2,
    ),
    SensorDevice(
        device_id="sensor-door-001",
        sensor_type=SensorType.DOOR_CONTACT,
        label="Door Contact — Emergency Exit E1",
        value_min=0.0,
        value_max=1.0,
        value_unit="open",
        value_decimals=0,
    ),
    SensorDevice(
        device_id="sensor-battery-001",
        sensor_type=SensorType.BATTERY,
        label="UPS Battery Health — Rack 4",
        value_min=0.0,
        value_max=100.0,
        value_unit="%",
        value_decimals=1,
    ),
]
