"""Sensor simulation — data models, simulation engine, and API routes.

This module replaces the previous split across sensor_models.py,
sensor_engine.py, and sensor_routes.py.
"""

from __future__ import annotations

import logging
import random
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

import fastapi
import config as sim_config
from fastapi.responses import JSONResponse

# ======================================================================
# Models
# ======================================================================


class SensorType(str, Enum):
    """Supported sensor measurement categories."""

    TEMPERATURE = "temperature"
    HUMIDITY = "humidity"
    PRESSURE = "pressure"
    LIGHT = "light"
    MOTION = "motion"
    AIR_QUALITY = "air_quality"
    LEAK = "leak"
    VIBRATION = "vibration"
    DOOR_CONTACT = "door_contact"
    BATTERY = "battery"


class SensorStatus(str, Enum):
    """Operational status of a sensor device."""

    OK = "ok"
    DEGRADED = "degraded"
    OFFLINE = "offline"
    ERROR = "error"


@dataclass
class SensorDevice:
    """Describes one virtual sensor device."""

    device_id: str
    sensor_type: SensorType
    label: str
    status: SensorStatus = SensorStatus.OK
    interval_seconds: int = 5
    battery_pct: float = 100.0
    signal_rssi_dbm: int = -55

    # Measurement bounds for realistic random generation
    value_min: float = 0.0
    value_max: float = 100.0
    value_unit: str = ""
    value_decimals: int = 1

    # Optional secondary value (e.g., occupancy count for motion)
    secondary_label: str = ""
    secondary_min: float = 0.0
    secondary_max: float = 0.0
    secondary_unit: str = ""

    # Current "drift anchor" so values change smoothly
    _current_value: float = 0.0
    _current_secondary: float = 0.0


@dataclass
class SensorReading:
    """A single telemetry reading generated by a sensor device."""

    device_id: str
    sensor_type: SensorType
    timestamp: datetime
    sequence: int
    status: SensorStatus
    battery_pct: float
    signal_rssi_dbm: int
    value: float
    unit: str
    secondary_value: Optional[float] = None
    secondary_unit: Optional[str] = None

    def to_facilix_payload(self) -> Dict[str, Any]:
        """Default Facilix-format payload."""
        values: Dict[str, Any] = {
            self.sensor_type.value: {
                "value": round(self.value, 2),
                "unit": self.unit,
            }
        }
        if self.secondary_value is not None and self.secondary_unit is not None:
            extra_label = "occupancy" if self.sensor_type == SensorType.MOTION else "value"
            values[extra_label] = {
                "value": round(self.secondary_value, 2),
                "unit": self.secondary_unit,
            }

        return {
            "deviceId": self.device_id,
            "sensorType": self.sensor_type.value,
            "timestamp": self.timestamp.isoformat(),
            "sequence": self.sequence,
            "status": self.status.value,
            "batteryPct": round(self.battery_pct, 1),
            "signalRssiDbm": self.signal_rssi_dbm,
            "values": values,
        }

    def to_thingsboard_payload(self) -> Dict[str, Any]:
        """ThingsBoard MQTT-style telemetry payload."""
        return {
            "ts": int(self.timestamp.timestamp() * 1000),
            "values": {
                self.sensor_type.value: round(self.value, 2),
                **({"occupancy": round(self.secondary_value, 2)} if self.secondary_value is not None else {}),
            },
        }

    def to_senml_payload(self) -> List[Dict[str, Any]]:
        """SenML (RFC 8428) compact representation."""
        records: List[Dict[str, Any]] = [
            {
                "n": self.sensor_type.value,
                "u": self.unit,
                "v": round(self.value, 2),
                "t": int(self.timestamp.timestamp()),
            }
        ]
        if self.secondary_value is not None and self.secondary_unit is not None:
            records.append(
                {
                    "n": "occupancy",
                    "v": round(self.secondary_value, 0),
                    "t": int(self.timestamp.timestamp()),
                }
            )
        records.append(
            {
                "n": "battery",
                "u": "%",
                "v": round(self.battery_pct, 1),
                "t": int(self.timestamp.timestamp()),
            }
        )
        records.append(
            {
                "n": "signal",
                "u": "dBm",
                "v": self.signal_rssi_dbm,
                "t": int(self.timestamp.timestamp()),
            }
        )
        return records

    def to_dict(self, fmt: str = "facilix") -> Dict[str, Any]:
        """Convert to dict in the requested format."""
        if fmt == "thingsboard":
            return self.to_thingsboard_payload()
        if fmt == "senml":
            return {"senml": self.to_senml_payload()}
        return self.to_facilix_payload()


# ---------------------------------------------------------------------------
# Sensor definition presets
# ---------------------------------------------------------------------------

SENSOR_DEFINITIONS: List[SensorDevice] = [
    SensorDevice(
        device_id="sensor-temp-001",
        sensor_type=SensorType.TEMPERATURE,
        label="Temperature Sensor — Main Lobby",
        value_min=18.0,
        value_max=30.0,
        value_unit="°C",
        value_decimals=1,
    ),
    SensorDevice(
        device_id="sensor-humidity-001",
        sensor_type=SensorType.HUMIDITY,
        label="Humidity Sensor — Warehouse A",
        value_min=30.0,
        value_max=70.0,
        value_unit="%RH",
        value_decimals=1,
    ),
    SensorDevice(
        device_id="sensor-pressure-001",
        sensor_type=SensorType.PRESSURE,
        label="Barometric Pressure — Outdoor",
        value_min=980.0,
        value_max=1040.0,
        value_unit="hPa",
        value_decimals=1,
    ),
    SensorDevice(
        device_id="sensor-light-001",
        sensor_type=SensorType.LIGHT,
        label="Ambient Light — Office South",
        value_min=0.0,
        value_max=1200.0,
        value_unit="lux",
        value_decimals=0,
    ),
    SensorDevice(
        device_id="sensor-motion-001",
        sensor_type=SensorType.MOTION,
        label="Motion Detector — Corridor B",
        value_min=0.0,
        value_max=1.0,
        value_unit="detected",
        value_decimals=0,
        secondary_label="occupancy_count",
        secondary_min=0.0,
        secondary_max=15.0,
        secondary_unit="people",
    ),
    SensorDevice(
        device_id="sensor-air-001",
        sensor_type=SensorType.AIR_QUALITY,
        label="Air Quality — Server Room",
        value_min=350.0,
        value_max=1200.0,
        value_unit="ppm",
        value_decimals=0,
        secondary_label="voc",
        secondary_min=0.0,
        secondary_max=500.0,
        secondary_unit="ppb",
    ),
    SensorDevice(
        device_id="sensor-leak-001",
        sensor_type=SensorType.LEAK,
        label="Leak Detector — Boiler Room",
        value_min=0.0,
        value_max=1.0,
        value_unit="leak",
        value_decimals=0,
    ),
    SensorDevice(
        device_id="sensor-vibration-001",
        sensor_type=SensorType.VIBRATION,
        label="Vibration Sensor — Pump Unit 3",
        value_min=0.0,
        value_max=25.0,
        value_unit="mm/s",
        value_decimals=2,
    ),
    SensorDevice(
        device_id="sensor-door-001",
        sensor_type=SensorType.DOOR_CONTACT,
        label="Door Contact — Emergency Exit E1",
        value_min=0.0,
        value_max=1.0,
        value_unit="open",
        value_decimals=0,
    ),
    SensorDevice(
        device_id="sensor-battery-001",
        sensor_type=SensorType.BATTERY,
        label="UPS Battery Health — Rack 4",
        value_min=0.0,
        value_max=100.0,
        value_unit="%",
        value_decimals=1,
    ),
]


# ======================================================================
# Engine
# ======================================================================

logger = logging.getLogger("simulator.sensors")

_devices: Dict[str, SensorDevice] = {}
_readings: Dict[str, List[SensorReading]] = {}
_latest: Dict[str, SensorReading] = {}
_device_enabled: Dict[str, bool] = {}
_sequence: Dict[str, int] = {}
_rng: random.Random


def init() -> None:
    """Initialize sensor simulator state from definitions."""
    seed = sim_config.RANDOM_SEED
    global _rng
    _rng = random.Random(seed)

    for dev in SENSOR_DEFINITIONS:
        dev.battery_pct = _rng.uniform(80.0, 100.0)
        dev.signal_rssi_dbm = _rng.randint(-70, -50)
        dev._current_value = _rng.uniform(dev.value_min, dev.value_max)
        dev._current_secondary = (
            _rng.uniform(dev.secondary_min, dev.secondary_max)
            if dev.secondary_min != dev.secondary_max
            else dev.secondary_min
        )

        _devices[dev.device_id] = dev
        _readings[dev.device_id] = []
        _latest[dev.device_id] = _generate_reading(dev)
        _device_enabled[dev.device_id] = True
        _sequence[dev.device_id] = 0

    logger.info("Initialized %d sensor devices", len(_devices))


# ---------------------------------------------------------------------------
# Reading generation
# ---------------------------------------------------------------------------


def _drift(
    current: float,
    target: float,
    max_step: float,
    min_val: float,
    max_val: float,
) -> float:
    """Move *current* toward *target* by at most *max_step*, then clamp."""
    if abs(current - target) < max_step:
        current = target
    elif current < target:
        current += _rng.uniform(0, max_step)
    else:
        current -= _rng.uniform(0, max_step)
    return max(min_val, min(max_val, current))


def _generate_reading(dev: SensorDevice) -> SensorReading:
    """Produce one reading for *dev*, mutating its internal drift state."""
    seq = _sequence.get(dev.device_id, 0)
    now = datetime.now(timezone.utc)

    # --- battery & signal decay -------------------------------------------
    if _rng.random() < 0.1:
        dev.battery_pct = max(0.0, dev.battery_pct - _rng.uniform(0.0, 0.5))
    # nudge signal up/down a little
    dev.signal_rssi_dbm += _rng.randint(-2, 2)
    dev.signal_rssi_dbm = max(-100, min(-30, dev.signal_rssi_dbm))

    # --- status simulation -------------------------------------------------
    if dev.battery_pct < 5.0:
        status = SensorStatus.OFFLINE
    elif dev.battery_pct < 15.0 or _rng.random() < 0.005:
        status = SensorStatus.DEGRADED
    else:
        status = SensorStatus.OK
    dev.status = status

    # --- value drift -------------------------------------------------------
    new_target = _rng.uniform(dev.value_min, dev.value_max)
    max_step = (dev.value_max - dev.value_min) * 0.05
    dev._current_value = _drift(dev._current_value, new_target, max_step, dev.value_min, dev.value_max)

    secondary: Optional[float] = None
    if dev.secondary_min != dev.secondary_max:
        sec_target = _rng.uniform(dev.secondary_min, dev.secondary_max)
        sec_step = (dev.secondary_max - dev.secondary_min) * 0.1
        dev._current_secondary = _drift(
            dev._current_secondary,
            sec_target,
            sec_step,
            dev.secondary_min,
            dev.secondary_max,
        )
        secondary = round(dev._current_secondary, 1)

    # --- motion / door / leak are boolean-ish ------------------------------
    value = dev._current_value
    if dev.sensor_type in (
        SensorType.MOTION,
        SensorType.DOOR_CONTACT,
        SensorType.LEAK,
    ):
        # Toggle occasionally
        if _rng.random() < 0.15:
            value = 1.0 if value < 0.5 else 0.0
            dev._current_value = value
        value = 1.0 if value >= 0.5 else 0.0
        if dev.sensor_type == SensorType.MOTION:
            secondary = _rng.randint(0, int(dev.secondary_max))

    reading = SensorReading(
        device_id=dev.device_id,
        sensor_type=dev.sensor_type,
        timestamp=now,
        sequence=seq,
        status=status,
        battery_pct=dev.battery_pct,
        signal_rssi_dbm=dev.signal_rssi_dbm,
        value=round(value, dev.value_decimals),
        unit=dev.value_unit,
        secondary_value=secondary,
        secondary_unit=dev.secondary_unit or None,
    )

    _sequence[dev.device_id] = seq + 1
    return reading


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_readings() -> Dict[str, SensorReading]:
    """Generate new readings for all enabled devices, store them, return latest."""
    generated: Dict[str, SensorReading] = {}
    for dev_id, dev in list(_devices.items()):
        if not _device_enabled.get(dev_id, True):
            continue
        reading = _generate_reading(dev)
        generated[dev_id] = reading
        _latest[dev_id] = reading
        hist = _readings[dev_id]
        hist.append(reading)
        if len(hist) > sim_config.SENSOR_HISTORY_LIMIT:
            _readings[dev_id] = hist[-sim_config.SENSOR_HISTORY_LIMIT :]
    return generated


def read_single(device_id: str) -> Optional[SensorReading]:
    """Force a single reading for a specific device."""
    dev = _devices.get(device_id)
    if dev is None:
        return None
    reading = _generate_reading(dev)
    _latest[device_id] = reading
    hist = _readings[device_id]
    hist.append(reading)
    if len(hist) > sim_config.SENSOR_HISTORY_LIMIT:
        _readings[device_id] = hist[-sim_config.SENSOR_HISTORY_LIMIT :]
    return reading


def get_devices() -> List[SensorDevice]:
    """Return all known sensor devices."""
    return list(_devices.values())


def get_device(device_id: str) -> Optional[SensorDevice]:
    """Return a single device by ID."""
    return _devices.get(device_id)


def get_latest(
    device_id: Optional[str] = None,
) -> Dict[str, SensorReading]:
    """Return latest reading(s). If device_id is None, return all."""
    if device_id:
        r = _latest.get(device_id)
        return {device_id: r} if r else {}
    return dict(_latest)


def get_history(device_id: str, limit: int = 100) -> List[SensorReading]:
    """Return recent history for a single device."""
    hist = _readings.get(device_id, [])
    return hist[-limit:]


def set_enabled(device_id: str, enabled: bool) -> bool:
    """Enable or disable automatic reading generation."""
    if device_id not in _device_enabled:
        return False
    _device_enabled[device_id] = enabled
    return True


def is_enabled(device_id: str) -> bool:
    """Check whether a device is currently enabled."""
    return _device_enabled.get(device_id, False)


# ======================================================================
# API Routes
# ======================================================================

router = fastapi.APIRouter(tags=["sensors"])


# ---------------------------------------------------------------------------
# Health (sensor-specific)
# ---------------------------------------------------------------------------


@router.get("/sensors/health")
async def sensors_health() -> JSONResponse:
    """Sensor-only health check."""
    total = len(get_devices())
    online = sum(1 for d in get_devices() if d.status.value in ("ok", "degraded"))
    return JSONResponse(
        {
            "status": "ok" if online == total else "degraded",
            "sensors": {"total": total, "online": online},
        }
    )


# ---------------------------------------------------------------------------
# Device listing
# ---------------------------------------------------------------------------


@router.get("/sensors")
async def list_sensors() -> JSONResponse:
    """List all configured sensor devices."""
    devices = get_devices()
    return JSONResponse(
        {
            "sensors": [
                {
                    "deviceId": d.device_id,
                    "sensorType": d.sensor_type.value,
                    "label": d.label,
                    "status": d.status.value,
                    "enabled": is_enabled(d.device_id),
                    "batteryPct": round(d.battery_pct, 1),
                    "signalRssiDbm": d.signal_rssi_dbm,
                    "intervalSeconds": d.interval_seconds,
                }
                for d in devices
            ]
        }
    )


@router.get("/sensors/{device_id}")
async def get_sensor(device_id: str) -> JSONResponse:
    """Get details for a single sensor device."""
    dev = get_device(device_id)
    if dev is None:
        return JSONResponse({"error": f"Device '{device_id}' not found"}, status_code=404)
    return JSONResponse(
        {
            "deviceId": dev.device_id,
            "sensorType": dev.sensor_type.value,
            "label": dev.label,
            "status": dev.status.value,
            "enabled": is_enabled(dev.device_id),
            "batteryPct": round(dev.battery_pct, 1),
            "signalRssiDbm": dev.signal_rssi_dbm,
            "intervalSeconds": dev.interval_seconds,
            "measurementRange": {
                "min": dev.value_min,
                "max": dev.value_max,
                "unit": dev.value_unit,
            },
        }
    )


# ---------------------------------------------------------------------------
# Readings
# ---------------------------------------------------------------------------


@router.get("/readings/latest")
async def get_latest_readings(device_id: Optional[str] = None) -> JSONResponse:
    """Get the latest reading(s). Optionally filter by device_id."""
    latest = get_latest(device_id)
    if not latest:
        return JSONResponse({"error": "No readings found"}, status_code=404)
    return JSONResponse({"readings": [r.to_dict(sim_config.SENSOR_PAYLOAD_FORMAT) for r in latest.values()]})


@router.get("/readings")
async def get_readings(device_id: str, limit: int = 100) -> JSONResponse:
    """Get recent reading history for a specific device."""
    if limit < 1:
        limit = 100
    dev = get_device(device_id)
    if dev is None:
        return JSONResponse({"error": f"Device '{device_id}' not found"}, status_code=404)
    history = get_history(device_id, limit=limit)
    return JSONResponse(
        {
            "deviceId": device_id,
            "count": len(history),
            "readings": [r.to_dict(sim_config.SENSOR_PAYLOAD_FORMAT) for r in history],
        }
    )


# ---------------------------------------------------------------------------
# Per-device actions
# ---------------------------------------------------------------------------


@router.post("/sensors/{device_id}/read")
async def read_now(device_id: str) -> JSONResponse:
    """Trigger a single immediate reading for a specific device."""
    reading = read_single(device_id)
    if reading is None:
        return JSONResponse({"error": f"Device '{device_id}' not found"}, status_code=404)
    return JSONResponse(reading.to_dict(sim_config.SENSOR_PAYLOAD_FORMAT))


@router.post("/sensors/{device_id}/start")
async def start_sensor(device_id: str) -> JSONResponse:
    """Enable automatic reading generation for a device."""
    ok = set_enabled(device_id, True)
    if not ok:
        return JSONResponse({"error": f"Device '{device_id}' not found"}, status_code=404)
    return JSONResponse({"status": "started", "deviceId": device_id})


@router.post("/sensors/{device_id}/stop")
async def stop_sensor(device_id: str) -> JSONResponse:
    """Disable automatic reading generation for a device."""
    ok = set_enabled(device_id, False)
    if not ok:
        return JSONResponse({"error": f"Device '{device_id}' not found"}, status_code=404)
    return JSONResponse({"status": "stopped", "deviceId": device_id})


# ---------------------------------------------------------------------------
# Backward compatibility endpoint for the monitoring server
# (src/server/main.py calls /devices/{simulation_device_id}/latest)
# ---------------------------------------------------------------------------


@router.get("/devices/{device_id}/latest")
async def get_device_latest(device_id: str) -> JSONResponse:
    """Get the latest reading for a device in a simple {value, status} shape."""
    latest = get_latest(device_id)
    reading = latest.get(device_id)
    if reading is None:
        return JSONResponse(
            {"error": f"No reading for device '{device_id}'"},
            status_code=404,
        )
    return JSONResponse(
        {
            "value": reading.value,
            "unit": reading.unit,
            "status": reading.status.value,
            "batteryPct": round(reading.battery_pct, 1),
            "timestamp": reading.timestamp.isoformat(),
        }
    )
